Repository Syonix/ha-wiser-by-feller, pull requests merged in 2025-05, with the labels that each got.

#4 Add Zeroconf support and fix dhcp discovery
  custom_components/wiser_by_feller/config_flow.py
  custom_components/wiser_by_feller/manifest.json
Labels: documentation, enhancement

#1 Do not load unused loads
  custom_components/wiser_by_feller/coordinator.py
Labels: enhancement, upstream

#11 Remove exception for HACS validation to allow failure
  .github/workflows/validate.yml
Labels: upstream
